mapped_labels = {
    "Acinetobacter.baumanii": 0,
    "Actinomyces.israeli": 1,
    "Bacteroides.fragilis": 2,
    "Bifidobacterium.spp": 3,
    "Candida.albicans": 4,
    "Clostridium.perfringens": 5,
    "Enterococcus.faecalis": 6,
    "Enterococcus.faecium": 7,
    "Escherichia.coli": 8,
    "Fusobacterium": 9,
    "Lactobacillus.casei": 10,
    "Lactobacillus.crispatus": 11,
    "Lactobacillus.delbrueckii": 12,
    "Lactobacillus.gasseri": 13,
    "Lactobacillus.jehnsenii": 14,
    "Lactobacillus.johnsonii": 15,
    "Lactobacillus.paracasei": 16,
    "Lactobacillus.plantarum": 17,
    "Lactobacillus.reuteri": 18,
    "Lactobacillus.rhamnosus": 19,
    "Lactobacillus.salivarius": 20,
    "Listeria.monocytogenes": 21,
    "Micrococcus.spp": 22,
    "Neisseria.gonorrhoeae": 23,
    "Porfyromonas.gingivalis": 24,
    "Propionibacterium.acnes": 25,
    "Proteus": 26,
    "Pseudomonas.aeruginosa": 27,
    "Staphylococcus.aureus": 28,
    "Staphylococcus.epidermidis": 29,
    "Staphylococcus.saprophiticus": 30,
    "Streptococcus.agalactiae": 31,
    "Veionella": 32,
}


mapped_labels_2 = {'Acinetobacter': 0, 'Actinomyces': 1, 'Bacteroides': 2, 'Bifidobacterium': 3, 'Candida': 4, 'Clostridium': 5, 'Enterococcus': 6, 'Escherichia': 7, 'Fusobacterium': 8, 'Lactobacillus': 9, 'Listeria': 10, 'Micrococcus': 11, 'Neisseria': 12, 'Porfyromonas': 13, 'Propionibacterium': 14, 'Proteus': 15, 'Pseudomonas': 16, 'Staphylococcus': 17, 'Streptococcus': 18, 'Veionella': 19}